[book]
title = 'cu-summer-stem-embedded-systems'
description = 'The Cooper Union - Summer STEM Embedded Systems: C-ing Beyond Arduino'
authors = [
  'Jacob Koziej',
]
language = 'en'

[build]
build-dir = 'build'

[output.html]
edit-url-template = 'https://github.com/jacobkoziej/cu-summer-stem-embedded-systems/edit/master/{path}'
git-repository-url = 'https://github.com/jacobkoziej/cu-summer-stem-embedded-systems'
hash-files = true
no-section-label = true
site-url = 'https://jacobkoziej.github.io/cu-summer-stem-embedded-systems/'
smart-punctuation = true
