---

name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master

      - name: build
        run: |
          nix \
          --extra-experimental-features 'nix-command flakes' \
          build \
          --print-build-logs \
          .#book

      - name: publish
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: result
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: '{long-sha}'
